### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JoestarK** [adria-gallart/3d_annotation_tool#1]
Hi, adria
  Thanks for your tool, but I got a problem while running ./Annotation_tool: Segmentation fault (core dumped)
  Here is the output of the gdb:
`GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Annotation_tool...(no debugging symbols found)...done.

warning: exec file is newer than core file.
[New LWP 12854]
[New LWP 12855]
[New LWP 12857]
[New LWP 12861]
[New LWP 12856]
[New LWP 12859]
[New LWP 12858]
[New LWP 12860]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./Annotation_tool'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.
[Current thread is 1 (Thread 0x7f7727165880 (LWP 12854))]
(gdb) bt

#0  strlen () at ../sysdeps/x86_64/strlen.S:106

#1  0x00007f772187b6a7 in ?? () from /usr/lib/x86_64-linux-gnu/libvtkRenderingCore-6.2.so.6.2

#2  0x00007f771e5ce7b1 in vtkAxisActor2D::vtkAxisActor2D() () from /usr/lib/libvtkRendering.so.5.10

#3  0x00007f771e5ce805 in vtkAxisActor2D::New() () from /usr/lib/libvtkRendering.so.5.10

#4  0x00007f771886cfbc in vtkLegendScaleActor::vtkLegendScaleActor() ()
   from /usr/lib/x86_64-linux-gnu/libvtkRenderingAnnotation-6.2.so.6.2

#5  0x00007f771886e50b in vtkLegendScaleActor::New() ()
   from /usr/lib/x86_64-linux-gnu/libvtkRenderingAnnotation-6.2.so.6.2

#6  0x00007f7725d4effb in pcl::visualization::PCLVisualizerInteractorStyle::Initialize() ()
   from /usr/lib/x86_64-linux-gnu/libpcl_visualization.so.1.7

#7  0x00007f7725d7be6a in pcl::visualization::PCLVisualizer::PCLVisualizer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libpcl_visualization.so.1.7

#8  0x000000000057d8b1 in viewerInteractor::viewerInteractor() ()

#9  0x000000000051f9d9 in MainWindow::MainWindow(QWidget*) ()

#10 0x000000000051d114 in main ()
`

**Comment by JoestarK** [comment]
My environments:
Ubuntu 16.04LTS
Qt4
VTK 6.2
PCL1.7

**Comment by adria-gallart** [comment]
Hi,

thanks for the information about the issue but unfortunately it's a long
time that I don't work with this tool (I am currently working in another
place) and I cannot give you support to solve any issue.

Sorry,

Adrià

2017-07-24 13:10 GMT+02:00 JoestarK <notifications@github.com>:
